
# True color support
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",*:RGB"
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g mouse on

# 1-based indexing for windows and panes
set -g base-index 1
set -g pane-base-index 1

# Alt+h/l to navigate windows
bind-key -n M-l next-window
bind-key -n M-h previous-window

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux#v2.1.3'

# Catppuccin configuration
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style 'rounded'

# Transparent status bar
set -g status-style 'bg=default'

# Status bar modules
set -g @catppuccin_window_default_text '#W'
set -g @catppuccin_window_current_text '#W'
set -g @catppuccin_status_left_separator '█'
set -g @catppuccin_status_right_separator '█'
set -g @catppuccin_status_background 'none'
set -g @catppuccin_pane_background_color 'none'

set -g status-left ''
set -g status-right '#{E:@catppuccin_status_session}'

setw -g mode-keys vi

# prefix + C-w: pick a directory with fzf and set it as the pane working directory
bind-key C-w run-shell "tmux neww 'dir=\$(find ~ -maxdepth 4 -type d 2>/dev/null | fzf --height=100% --prompt=\"Set working dir: \") && tmux attach-session -t \"#{session_name}\" -c \"\$dir\" && tmux display-message \"Working dir: \$dir\"'"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
