#!/bin/bash
# Setup wildcard DNS for *.dev.local → 127.0.0.2
# Works on Ubuntu/WSL with systemd-resolved or standalone dnsmasq

set -e

echo "==> Setting up wildcard DNS for *.dev.local → 127.0.0.2"

# Install dnsmasq if not present
if ! command -v dnsmasq &> /dev/null; then
    echo "==> Installing dnsmasq..."
    sudo apt-get update
    sudo apt-get install -y dnsmasq
fi

# Create dnsmasq config for dev.local
echo "==> Configuring dnsmasq..."
sudo tee /etc/dnsmasq.d/dev.local.conf > /dev/null << 'EOF'
# Resolve *.dev.local to 127.0.0.2 (for Traefik dev proxy)
address=/dev.local/127.0.0.2
EOF

# Check if systemd-resolved is running
if systemctl is-active --quiet systemd-resolved 2>/dev/null; then
    echo "==> Configuring systemd-resolved integration..."

    # Configure dnsmasq to not conflict with systemd-resolved
    sudo tee /etc/dnsmasq.d/systemd-resolved.conf > /dev/null << 'EOF'
# Listen on a different port, systemd-resolved will forward to us
port=5353
bind-interfaces
listen-address=127.0.0.1
EOF

    # Tell systemd-resolved to use dnsmasq for dev.local
    sudo mkdir -p /etc/systemd/resolved.conf.d
    sudo tee /etc/systemd/resolved.conf.d/dev-local.conf > /dev/null << 'EOF'
[Resolve]
DNS=127.0.0.1:5353
Domains=~dev.local
EOF

    echo "==> Restarting services..."
    sudo systemctl restart dnsmasq
    sudo systemctl restart systemd-resolved

else
    # WSL or system without systemd-resolved
    echo "==> Configuring standalone dnsmasq..."

    # Check if this is WSL
    if grep -qi microsoft /proc/version 2>/dev/null; then
        echo "==> WSL detected, configuring DNS..."

        # Disable WSL auto-generating resolv.conf
        if ! grep -q "generateResolvConf" /etc/wsl.conf 2>/dev/null; then
            sudo tee -a /etc/wsl.conf > /dev/null << 'EOF'

[network]
generateResolvConf = false
EOF
            echo "    Added generateResolvConf=false to /etc/wsl.conf"
        fi

        # Configure dnsmasq to forward to Windows DNS
        WINDOWS_DNS=$(grep nameserver /etc/resolv.conf 2>/dev/null | head -1 | awk '{print $2}')
        if [ -n "$WINDOWS_DNS" ]; then
            sudo tee /etc/dnsmasq.d/upstream.conf > /dev/null << EOF
# Forward other queries to Windows DNS
server=${WINDOWS_DNS}
EOF
        fi

        # Configure dnsmasq to listen on localhost
        sudo tee /etc/dnsmasq.d/local.conf > /dev/null << 'EOF'
listen-address=127.0.0.1
bind-interfaces
EOF

        # Update resolv.conf to use dnsmasq
        sudo rm -f /etc/resolv.conf
        sudo tee /etc/resolv.conf > /dev/null << 'EOF'
# Generated by setup-dns.sh for dev.local routing
nameserver 127.0.0.1
EOF

        echo "==> Restarting dnsmasq..."
        sudo systemctl restart dnsmasq 2>/dev/null || sudo service dnsmasq restart

        echo ""
        echo "==> WSL DNS configured!"
        echo "    NOTE: You may need to restart WSL for full effect:"
        echo "    wsl --shutdown (from Windows)"
    else
        # Regular Linux without systemd-resolved
        sudo systemctl restart dnsmasq
    fi
fi

echo ""
echo "==> Testing DNS resolution..."
if host test.dev.local 127.0.0.1 2>/dev/null | grep -q "127.0.0.2"; then
    echo "    ✓ test.dev.local resolves to 127.0.0.2"
else
    # Try nslookup as fallback
    if nslookup test.dev.local 127.0.0.1 2>/dev/null | grep -q "127.0.0.2"; then
        echo "    ✓ test.dev.local resolves to 127.0.0.2"
    else
        echo "    ⚠ DNS test inconclusive - try: ping test.dev.local"
    fi
fi

echo ""
echo "==> Setup complete!"
echo ""
echo "Usage:"
echo "  http://myproject.dev.local:3000  → frontend"
echo "  http://myproject.dev.local:9999  → backend"
echo "  localhost:3000                   → native dev (still works)"
